### PR TITLE
Add install section to readme

### PR DESCRIPTION
**Pull request by mfaerevaag**
First of all, awesome little hack. Works very well!

After installing on Arch Linux I thought I would add some notes to the readme, which may smooth the process for others in the future. Altough, the Makefile worked like a charm, there were some dependencies that were missing which I thought should be mentioned in the readme.

An altnernative, but maybe overkill, would be to add the build as a package to different package managers which could take care of dependency handling.

### CODE REVIEW

**Comment by hartwork** [comment]
Hello @mfaerevaag,
while I am happy about extending the readme that way, I would rather keep it Asciidoc over Markdown. If we were to turn it to Markdown, that should be a dedicated commit upfront at least.

**Comment by mfaerevaag** [comment]
Good idea. I have now made it a separate commit. 

If you prefer Asciidoc over Markdown I can also revert it to, if you'd like.

**Comment by hartwork** [comment]
Hello again,

looks better but with my picky hat on, there is more to find:
* The change from "About" to "grub2-theme-preview" doesn't fit that commit's overall aim and subject
* Same for changing `#` to `$`: It's not related to the transition to Markdown.
* qemu should be QEMU, I would say
* Links http://wiki.qemu.org/Main_Page and http://libburnia-project.org/ would make better targets in my eyes.

What do you think?

**Comment by mfaerevaag** [comment]
The intension of my pull-request was to add some insight to the depencies of the application.

I have amended the commit so it's up to par with your last comment. For any further details I suggest you pull the pull-request yourself.

**Comment by hartwork** [comment]
Thanks!
I took the liberty of reverting `$` back to `#` but kept and applied all else as-is.

**Comment by mfaerevaag** [comment]
Of course! Glad I could be of help.

**Pull request closed without merging**
